#!/usr/bin/env bash
set -Eeuo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
version="${1:-}"

case "$version" in
  4.0.1)
    revision="46a755b7ae45f818fce11db4df6cdccc16d8f9b5"
    migration="20260411070212"
    ;;
  4.2.0)
    revision="e8d24886f97f22469c2675f89be843f6d401c76a"
    migration="20260808090000"
    ;;
  *)
    echo "Usage: $0 4.0.1|4.2.0" >&2
    exit 2
    ;;
esac

command -v docker >/dev/null
docker info >/dev/null

image="teslamate/teslamate:$version"
network="odovi-teslamate-fixture-${version//./-}-$$"
database="odovi-teslamate-fixture-db-${version//./-}-$$"
application="odovi-teslamate-fixture-app-${version//./-}-$$"
raw_dump="$(mktemp "${TMPDIR:-/tmp}/odovi-teslamate-schema.XXXXXX")"
rendered_dump="$(mktemp "${TMPDIR:-/tmp}/odovi-teslamate-schema-rendered.XXXXXX")"
output="$repo_root/dev/fixtures/teslamate/v$version/schema.sql"

cleanup() {
  docker rm --force "$application" "$database" >/dev/null 2>&1 || true
  docker network rm "$network" >/dev/null 2>&1 || true
  rm -f "$raw_dump" "$rendered_dump"
}
trap cleanup EXIT
trap 'cleanup; exit 130' INT TERM

docker pull "$image"
actual_revision="$(docker image inspect "$image" --format '{{index .Config.Labels "org.opencontainers.image.revision"}}')"
if [[ "$actual_revision" != "$revision" ]]; then
  echo "TeslaMate $version revision mismatch: got $actual_revision, expected $revision." >&2
  exit 1
fi

docker network create "$network" >/dev/null
docker run --detach --name "$database" --network "$network" \
  --env POSTGRES_USER=teslamate \
  --env POSTGRES_PASSWORD=teslamate \
  --env POSTGRES_DB=teslamate \
  postgres:17-alpine >/dev/null

database_ready=0
for _ in {1..60}; do
  if docker exec "$database" pg_isready -U teslamate -d teslamate >/dev/null 2>&1; then
    database_ready=1
    break
  fi
  sleep 1
done
if [[ "$database_ready" != "1" ]]; then
  docker logs "$database" >&2
  echo "Disposable PostgreSQL database did not become ready." >&2
  exit 1
fi

docker run --detach --name "$application" --network "$network" \
  --env ENCRYPTION_KEY=fixture-generation-only \
  --env DATABASE_USER=teslamate \
  --env DATABASE_PASS=teslamate \
  --env DATABASE_NAME=teslamate \
  --env DATABASE_HOST="$database" \
  --env MQTT_HOST=unused-mqtt \
  "$image" >/dev/null

actual_migration="0"
for _ in {1..120}; do
  actual_migration="$(docker exec "$database" psql -U teslamate -d teslamate -Atc \
    'select coalesce(max(version), 0) from schema_migrations' 2>/dev/null || true)"
  if [[ "$actual_migration" == "$migration" ]]; then
    break
  fi
  if [[ "$(docker inspect --format '{{.State.Running}}' "$application" 2>/dev/null || true)" != "true" ]]; then
    docker logs "$application" >&2
    exit 1
  fi
  sleep 1
done

if [[ "$actual_migration" != "$migration" ]]; then
  docker logs "$application" >&2
  echo "TeslaMate $version stopped at migration $actual_migration; expected $migration." >&2
  exit 1
fi

docker exec "$database" pg_dump -U teslamate -d teslamate \
  --schema-only --no-owner --no-privileges >"$raw_dump"
mkdir -p "$(dirname "$output")"
{
  echo "--"
  echo "-- TeslaMate PostgreSQL schema dump"
  echo "--"
  echo "-- Source: $image (Docker Hub)"
  echo "--   image org.opencontainers.image.version = v$version"
  echo "--   image org.opencontainers.image.revision = $revision"
  echo "--   schema_migrations MAX(version) = $migration"
  echo "--"
  echo "-- Generated by scripts/generate-teslamate-schema-fixture.sh from the"
  echo "-- official TeslaMate image against a disposable postgres:17-alpine DB."
  echo "--"
  sed '/^\\restrict /d; /^\\unrestrict /d' "$raw_dump"
} >"$rendered_dump"
perl -0pi -e 's/\n+\z/\n/' "$rendered_dump"
mv "$rendered_dump" "$output"

echo "Wrote $output"
